# -*- Mode: YAML -*-

sudo: false # request container-base infrastructure
language: cpp

cache:
  apt: true
  directories:
    - ${HOME}/extra

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - cmake
            - cmake-data
            - git
            - libboost1.55-all-dev
            - g++-5
      env:
        - MATRIX_CC=gcc-5
        - MATRIX_CXX=g++-5
        - MATRIX_LCOV_ARGS="--gcov-tool gcov-5"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - cmake
            - cmake-data
            - git
            - libboost1.55-all-dev
            - g++-5
            - clang-3.7
      env:
        - MATRIX_CC=clang-3.7
        - MATRIX_CXX=clang++-3.7
        - MATRIX_LCOV_ARGS=""
        
before_script:
  - export CC=${MATRIX_CC} && ${CC} --version
  - export CXX=${MATRIX_CXX} && ${CXX} --version
  - export LCOV_ARGS=${MATRIX_LCOV_ARGS} && echo ${LCOV_ARGS}
  - mkdir ${TRAVIS_BUILD_DIR}/extra
  - mkdir ${TRAVIS_BUILD_DIR}/install
  - cd ${TRAVIS_BUILD_DIR}/extra
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - env PREFIX=${TRAVIS_BUILD_DIR}/install make -C lcov-1.11/ install
  - export PATH=${TRAVIS_BUILD_DIR}/install/usr/bin:${PATH}
  - lcov --version
  - gem install coveralls-lcov
  - export HUGH_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install
  - export HUGH_BUILDSYS_ROOT_DIR=${TRAVIS_BUILD_DIR}/extra/hugh-build-system
  - git clone --depth 1 http://github.com/regnirpsj/hugh-build-system.git ${HUGH_BUILDSYS_ROOT_DIR}
  - cd ${HUGH_BUILDSYS_ROOT_DIR} && mkdir build && cd build
  - cmake .. && cmake --build . --target install
  - export FETCHREPO=${HUGH_INSTALL_PREFIX}/share/hugh/travis.ci/fetch-or-update-git-repo.sh
  - export GLI_ROOT_DIR=${HOME}/extra/gli-git
  - export GLM_ROOT_DIR=${HOME}/extra/glm-git
  - ${FETCHREPO} http://github.com/g-truc/gli.git ${GLI_ROOT_DIR}
  - ${FETCHREPO} http://github.com/g-truc/glm.git ${GLM_ROOT_DIR}
  - export HUGH_SUPPORT_ROOT_DIR=${TRAVIS_BUILD_DIR}/extra/hugh-support
  - ${FETCHREPO} http://github.com/regnirpsj/hugh-support.git ${HUGH_SUPPORT_ROOT_DIR}
  - cd ${HUGH_SUPPORT_ROOT_DIR} && mkdir build && cd build
  - cmake .. && cmake --build . --target install
  - export HUGH_FIELDS_ROOT_DIR=${TRAVIS_BUILD_DIR}/extra/hugh-fields
  - ${FETCHREPO} http://github.com/regnirpsj/hugh-fields.git ${HUGH_FIELDS_ROOT_DIR}
  - cd ${HUGH_FIELDS_ROOT_DIR} && mkdir build && cd build
  - cmake .. && cmake --build . --target install
  - mkdir ${TRAVIS_BUILD_DIR}/build
  
script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DVERBOSE=1 -DHUGH_SCENE_COVERAGE=1 ..
  - cmake --build . --target test_coverage

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
